target-bigquery-repo-transfer
meltano/hub pull request #1016
Opened 2022-11-17 15:17 UTC by pnadolny13

Closes https://github.com/meltano/hub/issues/1014

2022-11-17 17:47 UTC, edgarrmondragon approved these changes

2022-11-17 17:47 UTC, edgarrmondragon commented on _data/meltano/loaders/target-bigquery/jmriego.yml
> +pip_url: pipelinewise-target-bigquery
I'd keep the PyPI reference. The maintainer has been publishing there.

2022-11-17 17:49 UTC, edgarrmondragon commented
> Did I do this right? I left transferwise as hidden and made a new one for the new maintainer repo.

@pnadolny13 Yeah, we gotta keep the transferwise variant 👍.

Should we add `jmriego` as a new maintainer?

2022-11-17 19:10 UTC, tayloramurphy requested changes
@pnadolny13 can you update the maintenance_status of the transferwise one to Inactive (or deprecated if we have that)?

Also, updated the next_steps section and/or description to note that the repo was transferred would be helpful for users too.

2022-11-18 13:26 UTC, pnadolny13 commented
> Should we add jmriego as a new maintainer?

Yes but interesting that the tests didnt fail for this, they are supposed to check for all maintainers existing. 🤔

2022-11-18 15:52 UTC, tayloramurphy approved these changes

2022-11-18 18:50 UTC, merged