fix command docs, remove args
meltano/hub pull request #1155
Opened 2023-02-07 15:09 UTC by pnadolny13

We currently show a [command section](https://hub.meltano.com/utilities/airflow#commands) on the utility pages that says you can run `meltano invoke airflow:create-admin [args...]` but I think this is a typo. You either have to not include the colon to run with args or no args are allowed. I'm not sure what way we want to recommend in the docs but this PR removes the reference to args.

2023-02-07 17:17 UTC, pnadolny13 commented
@tayloramurphy interesting, it looks like my understand was wrong 😞 . Thanks for that docs link. I thought that users could either use the colon to execute meltano commands with no support for arguments or if they did want to use arguments then they call the executable directly by excluding the colon. 

Testing a couple commands to clarify my understanding:

- `meltano invoke dbt-snowflake:seed --help` ✅ 
- `meltano invoke dbt-snowflake seed --help` ✅ 
- `meltano run dbt-snowflake:seed` ✅ 
- `meltano run dbt-snowflake:seed --help` ❌  returns the generic help text for the `meltano run` command same as if you ran `meltano run --help`

I can close this PR unless you still want me to make those other changes.

2023-02-07 22:30 UTC, tayloramurphy commented
@pnadolny13 that makes sense though - it only works on invoke and run doesn't accept additional args. 

@pnadolny13 I like this PR - just update the `meltano invoke` reference at the start of the section to link to the docs and I think we're good.

2023-02-13 23:19 UTC, pnadolny13 commented
@tayloramurphy I updated it to include the link!

2023-02-13 23:49 UTC, tayloramurphy approved these changes
Looks good!

2023-02-14 00:21 UTC, aaronsteers requested changes

2023-02-14 00:21 UTC, aaronsteers commented on src/components/PluginCommandsSection.vue
> +      ><code>meltano invoke {{ name }}:{{ command.name }}</code></pre>
This is correct as written, and I think noting `args...` as an optional input is helpful so users can discover this feature.

Should we revert this part back?

```suggestion
      ><code>meltano invoke {{ name }}:{{ command.name }} [args...]</code></pre>
```

As noted in the PR thread, the added args are freely supported in `invoke` - just not in `run`.

2023-04-26 15:30 UTC, closed without merging