feat: add tap-instantly-ai
meltano/hub pull request #1682
Opened 2024-02-19 14:44 UTC by bardrink

Adding a Meltano SDK tap for [Instantly AI](https://instantly.ai/).

2024-02-19 22:11 UTC, edgarrmondragon requested changes
Thanks @bardrink!

Just one comment about the missing logo.

2024-02-19 22:11 UTC, edgarrmondragon commented on _data/meltano/extractors/tap-instantly-ai/strvcom.yml
> +logo_url: /assets/logos/extractors/instantly-ai.png
Did you mean to add this?

2024-02-20 14:40 UTC, pnadolny13 commented on _data/meltano/extractors/tap-instantly-ai/strvcom.yml
> +quality: unknown
```suggestion
quality: silver
```

2024-02-20 14:41 UTC, pnadolny13 commented on _data/meltano/extractors/tap-instantly-ai/strvcom.yml
> +label: Tap Instantly AI
```suggestion
label: Instantly AI
```

2024-02-20 14:50 UTC, pnadolny13 commented on _data/meltano/extractors/tap-instantly-ai/strvcom.yml
> +description: Tap for Instantly AI
```suggestion
description: AI-powered cold email campaign management platform
```

2024-02-20 14:50 UTC, pnadolny13 approved these changes

2024-02-20 15:49 UTC, edgarrmondragon approved these changes
Thanks and congrats on your first addition to the Hub @bardrink!

2024-02-20 15:49 UTC, merged