refactor: :fire: remove `dialect+driver` and `sqlalchemy_url` from settings
meltano/hub pull request #1824
Opened 2024-08-27 12:25 UTC by tobiascadee

this target uses `redshift_connector` instead of sqlalchemy so removing those settings.

2024-08-28 01:57 UTC, edgarrmondragon requested changes

2024-08-28 01:57 UTC, edgarrmondragon commented on _data/meltano/loaders/target-redshift/ticketswap.yml
@tobiascadee there are other references to `sqlalchemy_url` in some of the settings, should we update them too?

2024-08-28 11:09 UTC, tobiascadee commented on _data/meltano/loaders/target-redshift/ticketswap.yml
yes, will do! do you also want me to incorporate [your changes ](https://github.com/meltano/hub/pull/1819) in here as well?

2024-08-28 13:58 UTC, edgarrmondragon commented on _data/meltano/loaders/target-redshift/ticketswap.yml
It's fine to keep separate PRs

2024-08-29 15:10 UTC, edgarrmondragon approved these changes
Thanks @tobiascadee!

2024-08-29 15:10 UTC, merged