[feat] Add dbt osmosis utility to hub
meltano/hub pull request #766
Opened 2022-09-07 03:50 UTC by z3z1ma

Adds the dbt osmosis utility to meltano hub.

## Checklist

- [ ] Add/update the file in the appropriate folder (`/taps` or `/targets`). The name of the file should match the name of the tap. If there is already one, add a descriptor to the name such as `-search`.
- [ ] Add/update the PNG logo image in `/assets/logos/<taps or targets>`. The image name must match the YAML file name.
- [ ] Tag `@tayloramurphy` or `@pnadolny13` to flag it for review. Or post to the [#hub](https://meltano.slack.com/archives/C01UGBSJNG5) channel on Meltano slack.

## Reviewer Checklist

- [ ] Validate file against JSON Schema. https://www.jsonschema.net/home is an option.
- [ ] Build website locally and validate everything works.

2022-09-07 03:50 UTC, z3z1ma commented
@tayloramurphy @pnadolny13 

Up for review!

2022-09-09 18:53 UTC, tayloramurphy requested changes
Just a few text changes, but it's looking good! Preview is here https://deploy-preview-766--meltano-hub.netlify.app/utilities/dbt-osmosis

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +definition: A tool to supercharge dbt development by providing 3 key functions.
```suggestion
definition: |
   is a tool to supercharge [dbt](https://docs.getdbt.com/) development by providing 3 key functions:
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  2. The ability to diff model outputs across file revisions,
```suggestion
  2. The ability to diff model outputs across file revisions
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  3. Automation which manages generating, updating, and propagate documentation for your
```suggestion
  3. Automation which manages generating, updating, and propagating documentation for your
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  schema yaml files.
```suggestion
  `schema.yml` files.
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  Additionally, a server for VS code to allow quickly previewing models
```suggestion
  Additionally, a server for VS code enables quickly previewing models
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  when used in conjunction with https://github.com/datacoves/vscode-dbt-power-user
```suggestion
  when used in conjunction with the [VSCode dbt power user extension](https://github.com/datacoves/vscode-dbt-power-user).
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  though the server can be used for anything.
```suggestion
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +      dbt and its profile directory into transform/&lt;adapter&gt; directory. We use this
```suggestion
      dbt and its profile directory into `transform/<adapter>` directory. We use this 
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  1. Add dbt-&lt;adapter&gt; to your pip_url, ie: `pip_url: dbt-osmosis dbt-bigquery`
```suggestion
  1. Add dbt-<adapter> to your pip_url, ie: `pip_url: dbt-osmosis dbt-bigquery`
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  2. Override the namespace to mirror your dbt adapter, ie: `namespace: dbt_bigquery`
```suggestion
  1. Override the namespace to mirror your dbt adapter, ie: `namespace: dbt_bigquery`
```

2022-09-09 18:53 UTC, tayloramurphy commented on _data/meltano/utilities/dbt-osmosis/z3z1ma.yml
> +  3. Mirror the configuration set in your dbt-&lt;adapter&gt; plugin. A simple copy-paste of
```suggestion
  1. Mirror the configuration set in your dbt-<adapter> plugin. A simple copy-paste of
```

2022-10-06 19:46 UTC, tayloramurphy approved these changes
This looks good to me. @pnadolny13 can you review and merge if you approve?

2022-10-07 15:17 UTC, pnadolny13 commented
@z3z1ma One last thing you just need to move your logo because the `assets/logos/..` directory was migrated into `static/assets/logos/..`. Then I should be able to test an add from my project just to verify its working as expected.

2022-10-07 18:10 UTC, z3z1ma commented
@pnadolny13 

Got it, all done -- give it a whirl!

2022-10-10 11:13 UTC, merged