Standardize logo, text, alignment for plugin grids
meltano/hub pull request #834
Opened 2022-09-22 20:15 UTC by cjohnhanson

Closes #833

2022-09-22 20:25 UTC, rwfeather commented
Plugin grid seems tricky to get right, now the multi-line names are overlapping logos:

<img width="712" alt="Screen Shot 2022-09-22 at 3 20 04 PM" src="https://user-images.githubusercontent.com/6589528/191844075-5bad5d66-eb72-44de-b55a-817fd46eeac9.png">

Feels like something has got to give with the varying logo and text sizes.

2022-09-22 20:26 UTC, rwfeather approved these changes

2022-09-22 20:26 UTC, rwfeather commented on src/pages/Extractors.vue
> +              <p class="font-bold underline text-xs lg:text-md justify-self-center text-clip" e>
Extra text "e" in these

2022-09-22 21:09 UTC, cjohnhanson commented
> Plugin grid seems tricky to get right, now the multi-line names are overlapping logos:

@rwfeather yeah I think what we want here would be "make all cards the height of the the tallest content and put them in a 4-column grid". Sizing would be easier to do with flexbox but the grid obviously is easier to do with grid.

2022-09-22 21:31 UTC, tayloramurphy requested changes
@cjohnhanson anything we can do about that overlap? I'd be cool with assuming 2 lines of text and keeping logos to the max size of CSV (or whatever the largest one is).

Also, I just noticed that the alphabetization is case sensitive ![Screen Shot 2022-09-22 at 4 30 40 PM](https://user-images.githubusercontent.com/5394188/191854763-12b1c1ef-7cb2-45e6-bef8-6aa263bf3695.png)

2022-09-23 06:22 UTC, aaronsteers commented
> I'd be cool with assuming 2 lines of text

Agreed. Let's assume 1 or 2 lines of text max.

2022-09-23 17:36 UTC, cjohnhanson commented
@tayloramurphy @aaronsteers I took another pass at this this morning with hard-coded heights and it's looking better at the screen sizes I checked out. I also updated sorting to be case insensitive.

2022-09-23 18:34 UTC, tayloramurphy approved these changes
Love the changes! Looks great

2022-09-23 19:14 UTC, aaronsteers approved these changes
Looks really good! Thanks, @cjohnhanson !

2022-09-23 20:44 UTC, merged