add metabase plugin
meltano/hub pull request #865
Opened 2022-10-02 21:52 UTC by pnadolny13

2022-10-03 17:00 UTC, tayloramurphy commented
@pnadolny13 to your point about the empty pip_url - that's partially because of a JSON validation, right? It seems like if we implemented https://github.com/meltano/meltano/discussions/6459 we could make it optional.

2022-10-03 18:22 UTC, pnadolny13 commented
> @pnadolny13 to your point about the empty pip_url - that's partially because of a JSON validation, right? It seems like if we implemented [meltano/meltano#6459](https://github.com/meltano/meltano/discussions/6459) we could make it optional.

Yeah right now the json schemas require that pip_url is present. So the tests were failing but an empty string looks to pass, I wonder if theres other weird implications if the `meltano add` logic assumes a pip install which would fail for this.

2022-10-05 12:50 UTC, pnadolny13 commented
@rwfeather @edgarrmondragon @cjohnhanson @aaronsteers I need a little help testing that this will work when I merge. I include an empty pip_url since this is container only. Will that causes installation failures? I tried to install by pointing my meltano instance at a local hub api instance (and the deploy preview) but neither worked because it looks like its requesting the correct index url, then following the links returned but the links returned always have the default https://hub.meltano.com/ base url so they fail since it doesnt exist there yet.

Any thoughts on how to test it? I imagine we'll probably want to have the hub api logic to propagate the non-default url throughout when its generating the static API. Potentially also evaluating a container only option where pip url isnt required.

2022-10-05 14:45 UTC, aaronsteers commented
@pnadolny13 - You should be able to leave pip_url out altogether. Can you confirm if that approach works? 

Regarding the API URL root, let's see if we can target a branch as root using raw URL syntax....

@tayloramurphy We may also want consider logging and/or prioritizing the `meltano add --from_ref=...` approach where we point to the URL for a lock file or plugin definition directly. That would make installation of plugins much easier, directly from their own repo or from a test definition.

2022-10-05 15:35 UTC, pnadolny13 commented
> @pnadolny13 - You should be able to leave pip_url out altogether. Can you confirm if that approach works?

@aaronsteers the plugin does works in meltano without the pip_url defined if I install it myself but I'm wondering if the install will fail if the pip_url in this hub definition is null i.e. does meltano run `pip install {plugin_definition_json.get('pip_url')}` when something is added? In that case I would expect the add/installation of this plugin to fail. Right?

> Regarding the API URL root, let's see if we can target a branch as root using raw URL syntax....

I don't think I follow this part, can you explain more?

To add detail in case my first comment wasn't super clear, right now if I request the index from the preview app it includes metabase (great!) but the entry looks like:

https://deploy-preview-865--meltano-hub.netlify.app/meltano/api/v1/plugins/utilities/index

```
    "metabase": {
        "variants": {
            "metabase": {
                "ref": "https://hub.meltano.com/meltano/api/v1/plugins/utilities/metabase--metabase"
            }
        },
        "default_variant": "metabase",
        "logo_url": "https://hub.meltano.com/assets/logos/utilities/metabase.png"
    }
```

So when meltano follows the `ref` to get the plugin definition json, it fails because the prod url doesnt exist yet.

Does that make sense?

2022-10-05 17:18 UTC, rwfeather commented
@edgarrmondragon @pnadolny13 I've readied a fix for the above issue that's preventing you from testing this change

- #876 

Running `gridsome develop` still seems to skip generating the API for some reason, but I can confirm that this should work for netlify preview builds

2022-10-05 20:05 UTC, edgarrmondragon requested changes
@pnadolny13 you might need to move the logo from `assets/logos/utilities/metabase.png` to `static/assets/logos/utilities/metabase.png`.

2022-10-05 20:20 UTC, aaronsteers commented
> does meltano run `pip install {plugin_definition_json.get('pip_url')}` when something is added?

If `pip_url` is simply not there, it should skip attempting to install anything via pip.

2022-10-05 20:22 UTC, aaronsteers commented
> I've readied a fix for the above issue that's preventing you from testing this change

Thanks, @rwfeather !

2022-10-05 20:25 UTC, aaronsteers commented
Looking good! https://deploy-preview-865--meltano-hub.netlify.app/meltano/api/v1/plugins/utilities/index


```js
{
// ...
   "metabase":{
      "variants":{
         "metabase":{
            "ref":"https://deploy-preview-865--meltano-hub.netlify.app/meltano/api/v1/plugins/utilities/metabase--metabase"
         }
      },
      "default_variant":"metabase",
      "logo_url":"https://deploy-preview-865--meltano-hub.netlify.app/assets/logos/utilities/metabase.png"
   },
// ...
}
```

2022-10-05 20:55 UTC, edgarrmondragon approved these changes

2022-10-05 21:04 UTC, cjohnhanson approved these changes

2022-10-05 21:10 UTC, pnadolny13 commented
@rwfeather thanks! It looks like I'm able to test and everything now.

>If pip_url is simply not there, it should skip attempting to install anything via pip.

@aaronsteers I was able to test it and it looks like it does fail to install because this definition has an empty string for the pip_url, although the plugin definition and meltano.yml entry still get added. So I'm able to then spin it up but I still got an ugly install error.

![Screen Shot 2022-10-05 at 4 30 51 PM](https://user-images.githubusercontent.com/27376735/194157507-9d5df3e8-95bf-4ae8-9811-638dffc7c48b.png)

We have 2 conflicting rules right now:
- the hub plugin definition JSON schemas require `pip_url` to not be null
- meltano looks like it needs `pip_url` to be null in order to know to skip the "pip install"

2022-10-05 21:28 UTC, aaronsteers commented on _data/meltano/utilities/metabase/metabase.yml
> +pip_url: ''
```suggestion
```

Distinction of leaving out entirely vs leaving blank.

@pnadolny13 - Can you try this way with the field left out?

2022-10-05 21:31 UTC, aaronsteers commented
My expectation is that `pip_url` should be optional everywhere, but when it is specified, it needs to be a valid completion to the command `pip install ...`.

2022-10-06 00:43 UTC, pnadolny13 commented
> My expectation is that `pip_url` should be optional everywhere, but when it is specified, it needs to be a valid completion to the command `pip install ...`.

@aaronsteers ok that makes sense - I meant that the hub schema definition for plugins require it in https://github.com/meltano/hub/blob/ac95d95ca2bd94eea24b8ffd36ca0e18b75ba143/schemas/common/common.schema.json#L11 so CI tests fail. If thats not a requirements we can remove that from the schema though, I didnt know that.

2022-10-06 01:15 UTC, aaronsteers commented
> > My expectation is that `pip_url` should be optional everywhere, but when it is specified, it needs to be a valid completion to the command `pip install ...`.
> 
> @aaronsteers ok that makes sense - I meant that the hub schema definition for plugins require it in https://github.com/meltano/hub/blob/ac95d95ca2bd94eea24b8ffd36ca0e18b75ba143/schemas/common/common.schema.json#L11 so CI tests fail. If thats not a requirements we can remove that from the schema though, I didnt know that.

Cool. Yeah, totally makes sense. We can update that json schema as needed. 👍

I believe this requirement was removed back when we introduced docker support in commands. But it's not widely used at this point so I think this might be the first thing added to the hub without a pip_url.

2022-10-06 15:49 UTC, edgarrmondragon commented
> What do we think the best path is for the local metabase data like the db it creates? I put it in `$MELTANO_PROJECT_ROOT/analyze/metabase/` but its not something that would be checked into git so maybe its better to go in `$MELTANO_PROJECT_ROOT/.meltano/utilities/metabase/data/`? Or `$MELTANO_PROJECT_ROOT/.meltano/run/metabase/data`? Is there conventions for where things go in the `.meltano` folder?

@pnadolny13 You're right, `.meltano` is a better place for it. That's what superset does: https://github.com/meltano/hub/pull/865#issuecomment-1270286465

2022-10-06 16:45 UTC, aaronsteers commented
@pnadolny13 - The `.meltano` directory can definitely work, and that's also where we put hidden dbt artifacts by default. I assume we don't have a repo scaffold or extension as of yet, correct?

The extension (if we add one later) can install a custom `.gitignore` as well as other files.

2022-10-06 16:47 UTC, aaronsteers approved these changes

2022-10-06 16:47 UTC, aaronsteers commented on schemas/common/common.schema.json
> -        "pip_url",
👍

2022-10-06 16:48 UTC, aaronsteers commented
My review doesn't cover everything, but for my part, this looks good! 👍 ✅

2022-10-06 16:59 UTC, pnadolny13 commented
Thanks @aaronsteers @edgarrmondragon. I moved it into the `.meltano` dir. We can have a follow on to add functionality with the EDK, sounds like from https://meltano.slack.com/archives/C013Z450LCD/p1654800904252579 that @z3z1ma has already made progress on that.

2022-10-06 16:59 UTC, merged