Gainsightpx
meltano/hub pull request #976
Opened 2022-10-28 00:28 UTC by jlloyd-widen

@tayloramurphy @pnadolny13 

## Checklist

- [ x] Add/update the file in the appropriate folder (`/taps` or `/targets`). The name of the file should match the name of the tap. If there is already one, add a descriptor to the name such as `-search`.
- [ x] Add/update the PNG logo image in `/assets/logos/<taps or targets>`. The image name must match the YAML file name.
- [ x] Tag `@tayloramurphy` or `@pnadolny13` to flag it for review. Or post to the [#hub](https://meltano.slack.com/archives/C01UGBSJNG5) channel on Meltano slack.

## Reviewer Checklist

- [ ] Validate file against JSON Schema. https://www.jsonschema.net/home is an option.
- [ ] Build website locally and validate everything works.

2022-10-28 00:39 UTC, edgarrmondragon requested changes

2022-10-28 00:39 UTC, edgarrmondragon commented on _data/meltano/extractors/tap-gainsightpx/Widen.yml
> +- tap
```suggestion
- tap
- meltano_sdk
```

2022-10-28 16:03 UTC, tayloramurphy requested changes
@jlloyd-widen can you also add an entry in https://github.com/jlloyd-widen/hub/blob/gainsightpx/_data/default_variants.yml#L167 to add tap-gainsightpx? It looks like we don't have that on our checklist currently, but the site won't build without it. Sorry about that!

2022-10-28 16:03 UTC, tayloramurphy commented on _data/meltano/extractors/tap-gainsightpx/Widen.yml
> +variant: Widen
```suggestion
variant: widen
```

2022-10-28 16:48 UTC, jlloyd-widen commented
> @jlloyd-widen can you also add an entry in https://github.com/jlloyd-widen/hub/blob/gainsightpx/_data/default_variants.yml#L167 to add tap-gainsightpx? It looks like we don't have that on our checklist currently, but the site won't build without it. Sorry about that!

@tayloramurphy Done

2022-10-31 20:39 UTC, pnadolny13 commented on _data/meltano/extractors/tap-gainsightpx/Widen.yml
> +- api_url
```suggestion
- - api_url
  - client_id
  - client_secret
  - refresh_token
  - start_date
```

@jlloyd-widen this key is a list of lists so it needs to be nested one more level deep.

2022-10-31 20:40 UTC, pnadolny13 commented on _data/meltano/extractors/tap-gainsightpx/Widen.yml
> +  description: 'True' to enable schema flattening and automatically expand nested properties.
```suggestion
  description: "'True' to enable schema flattening and automatically expand nested properties."
```
@jlloyd-widen the single quotes were causing a yaml syntax error. Popping them in double quotes looks to fix it 👍 .

2022-10-31 20:41 UTC, pnadolny13 requested changes
@jlloyd-widen thanks for the PR! I left a couple more comments but other than those it looks good to go.

2022-11-01 13:03 UTC, pnadolny13 approved these changes

2022-11-01 14:01 UTC, pnadolny13 commented
@jlloyd-widen looks good I'll merge it in - thanks again for the PR and the quick fixes!

2022-11-01 14:01 UTC, merged